name: verification
type: php
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - DRUPAL_CORE_CONSTRAINT=^9
  - COMPOSER=composer.spoons.json
  - WEB_ROOT=web
  - NONINTERACTIVE=1
  - COMPOSER_NO_INTERACTION=1
  - WEB_PORT=9000
  - SIMPLETEST_BASE_URL=http://localhost
  - SIMPLETEST_DB=sqlite://localhost/sites/default/files/.sqlite
nodejs_version: "16"
hooks:
  post-start:
    - exec: "rm .composer-plugin.env composer.spoons.json composer.spoons.lock || true"
    - exec: "bash <(curl -s https://gitlab.com/drupalspoons/composer-plugin/-/raw/master/bin/setup)"
    - exec: "drush status"
  post-stop:
    - exec-host: "rm -rf web vendor"
