name: Lint & Test

on:
  push:
    branches:
      - 1.0.x
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - drupal: "10"
            php: "8.2"
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install drupal
        run: bash <(curl -s https://gitlab.com/drupalspoons/composer-plugin/-/raw/master/bin/setup)
        env:
          DRUPAL_CORE_CONSTRAINT: ${{ matrix.drupal }}

      - name: Lint
        run: composer run-script phpcs

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - drupal: "9"
            php: "8.1"
          - drupal: "10"
            php: "8.1"
          - drupal: "10"
            php: "8.2"
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install drupal
        run: bash <(curl -s https://gitlab.com/drupalspoons/composer-plugin/-/raw/master/bin/setup)
        env:
          DRUPAL_CORE_CONSTRAINT: ${{ matrix.drupal }}

      - name: Test
        run: composer run-script unit
